publish_period: 0.01
max_expected_latency: 0.1
# incoming_command_timeout: 10.0

command_in_type: speed_units
scale:
  linear: 0.2
  rotational: 0.8
  joint: 0.5

publish_joint_positions: false
publish_joint_velocities: true
publish_joint_acclerations: false

use_smoothing: true
smoothing_filter_plugin_name: "online_signal_smoothing::AccelerationLimitedPlugin"

is_primary_planning_scene_monitor: true
check_octomap_collisions: false

move_group_name: arm

lower_singularity_threshold: 2000.0
hard_stop_singularity_threshold: 2001.0
leaving_singularity_threshold_multiplier: 2.0

joint_limit_margins:
- 0.12
- 0.12
- 0.12
- 0.12
- 0.12
- 0.12

cartesian_command_in_topic: ~/delta_twist_cmds
joint_command_in_topic: ~/delta_joint_cmds
joint_topic: /joint_states
status_topic: ~/status
# command_out_topic: /trajectory_controller/joint_trajectory
# command_out_type: trajectory_msgs/JointTrajectory
command_out_topic: /velocity_controller/commands
command_out_type: std_msgs/Float64MultiArray


check_collisions: false
